/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.eclipsejdt.gettingstarted;

import java.util.Set;

public class Library {
    public boolean someLibraryMethod() {
    	System.out.println("I am "
    			+ "new line");
        return true;
    }
}
